name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Node.js and npm informations
        run: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

      - name: Install dependencies
        run: npm ci

      - name: "Unit tests"
        run: "npm run test"

      - name: "Build"
        run: "npm run build"
